### PR TITLE
Implement folo record stored for archived content download

### PR DESCRIPTION
**Pull request by yma88**
Refactor some of the folo report part in Sidecar, the archived folo store request to Indy endpoint: https://github.com/Commonjava/indy/pull/2264.
Nowadays archived tracking record ones will be stored in Indy, proxy ones(non-archived) will reach to Indy /folo/track then store through the tracking listener. After seal request, the folo report would be intact from Indy.
Folo import in sidecar would just for maintenance purpose.

### CODE REVIEW

**Review by ligangty — COMMENTED** [review]
I need to confirm the process. Does the sidecar do the folo tracking in batch mode or single mode? I mean for the TrackedContentEntry. Seems the code shows it is sending the entry through one single client call for each one. I'm really concerning the performance of this way.

**Comment by yma88** [comment]
@ligangty should be single mode. If using batch mode, PNC might need to execute folo record import from sidecar after build is finished, since sidecar doesn't know when is the end of one build.

**Comment by ligangty** [comment]
> @ligangty should be single mode. If using batch mode, PNC might need to execute folo record import from sidecar after build is finished, since sidecar doesn't know when is the end of one build.

I'm thinking if we can organize a self-defined batch, like batch-sized, or scheduled batch. For example, we can set a batch of 50 entries, or schedule a time of 5s for each batch. (Maybe scheduler is better because we don't know the final batch size)

But for complexity consideration, maybe the 1st version we can keep single mode to have a try, and see how the performance looks. In the meantime maybe you can have a research on how to do the batch sending more gracefully.

**Comment by ligangty** [comment]
BTW, do we have some re-try for the web-client used in the entry sending?

**Comment by yma88** [comment]
> BTW, do we have some re-try for the web-client used in the entry sending?

Yes, when consuming it uses WebClientAdapter to wrap the retry.

**Comment by yma88** [comment]
> > @ligangty should be single mode. If using batch mode, PNC might need to execute folo record import from sidecar after build is finished, since sidecar doesn't know when is the end of one build.
> 
> I'm thinking if we can organize a self-defined batch, like batch-sized, or scheduled batch. For example, we can set a batch of 50 entries, or schedule a time of 5s for each batch. (Maybe scheduler is better because we don't know the final batch size)
> 
> But for complexity consideration, maybe the 1st version we can keep single mode to have a try, and see how the performance looks. In the meantime maybe you can have a research on how to do the batch sending more gracefully.
> 
> For the code itself, I agree to merge if we keep single mode.


For each entry storing, Indy also has the folo listener for each tracked file access, so the db io perf should be accepted. For folo http requests load, sidecar uses event bus which performs asynchronously from the content download.
I agree a better way to tuning event bus async operations, like vertx one-shot timers to see the perf improvement.
Will keep eyes on this, @ligangty thanks for the suggestion!

**Pull request merged**
