### PR TITLE
Send http header proxy-origin to rewrite npm meta tarball url

### PR DESCRIPTION
**Pull request by yma88**

### CODE REVIEW

**Review by ruhan1 — APPROVED** [review]
LGTM. somehow the test failed?

**Comment by ruhan1** [comment]
retest this please

**Comment by yma88** [comment]
> LGTM. somehow the test failed?

@ruhan1 I check the jenkins is built on galley repo ;-( correct it in the Jenkinsfile.

**Comment by ruhan1** [comment]
:+1:

**Pull request merged**
